### ISSUE TITLE
gathering all data from UH50

### ISSUE THREAD

**Issue by ervu** [vpathuis/ultraheat#9]
Hi,

Great project and I am recently using the HA plugin to extract data from the UH50. 

Is it also possible to extract more data from the UH50?
The UH50 has much live counters available via the front panel like actual power ussage and temperature delta's.

Thanks

**Comment by vpathuis** [comment]
Hi @ervu , thanks for contacting! 
I've not yet come across actual power and temperature deltas in the 'telegram' that is returned from the heat meter. If you have a look at [this documentation](https://github.com/vpathuis/ultraheat#telegram-parsing), you'll see that almost all is parsed already and I don't see any data that could be what you're looking for. But if you do, let me known, because then it can be added easily!

**Comment by ervu** [comment]
Hi, thanks for the response!
I could be possible that the UH50 live diag data is only available via hidden commands. The current data is sufficient to use and analyze and I am very happy that i have insights in out heat consumption. Vattenfall has be talking for years about their "WarmteLink" and now they are deploying that. ETA: before the end of 2027 ... LOL

**Comment by vpathuis** [comment]
It would be very interesting to know about more commands that give additional data, but I've not been able to find info about that. Great to hear that you're happy with the integration! 
I'll close this issue for now. If you have more info or other questions, feel free to open up another issue.
